/**
 * LedgerEntry factory — Pilot Onboarding Hardening Sprint PD.1.2
 *
 * Pins that `createLedgerEntryEntity` accepts the new
 * `'opening_balance'` entryType (PD.0.1) and produces an entity with
 * the canonical `LEDGER#{accountId}#{entryId}` SK shape that the
 * existing ledger query patterns rely on.
 *
 * Existing entry types (`'invoice' | 'payment' | 'refund' |
 * 'adjustment' | 'write_off'`) are exercised by the broader finance
 * suite — this spec narrowly proves the new value flows through.
 */

import { createLedgerEntryEntity } from './ledger-entry.entity';

const TENANT_ID = '11111111-1111-4111-8111-111111111111';
const ACCOUNT_ID = '22222222-2222-4222-8222-222222222222';
const STUDENT_ID = '33333333-3333-4333-8333-333333333333';
const USER_ID = '44444444-4444-4444-8444-444444444444';

describe('createLedgerEntryEntity — PD.1.2 opening_balance support', () => {
  it('accepts opening_balance entryType and emits the canonical LEDGER#{accountId}#{entryId} SK', () => {
    const entry = createLedgerEntryEntity(
      TENANT_ID,
      {
        studentAccountId: ACCOUNT_ID,
        studentId: STUDENT_ID,
        entryType: 'opening_balance',
        referenceId: 'opening-balance-set',
        description: 'Opening balance — carry-forward from BS 2082',
        debit: 5000,
        credit: 0,
        balance: 5000,
        date: '2026-04-12',
      },
      USER_ID,
    );

    expect(entry.entryType).toBe('opening_balance');
    expect(entry.entityType).toBe('LEDGER_ENTRY');
    expect(entry.tenantId).toBe(TENANT_ID);
    // SK format invariant: LEDGER#{accountId}#{entryId} — entryId is
    // a UUID generated by the factory; matching that pattern proves
    // the new entryType doesn't disturb key construction.
    expect(entry.entityKey).toMatch(
      new RegExp(`^LEDGER#${ACCOUNT_ID}#[0-9a-f-]{36}$`),
    );
    expect(entry.debit).toBe(5000);
    expect(entry.credit).toBe(0);
    expect(entry.balance).toBe(5000);
    expect(entry.date).toBe('2026-04-12');
    expect(entry.studentId).toBe(STUDENT_ID);
    // GSI2 student-scope key still set (required for the
    // student-ledger query at `/finance/students/:id/ledger`).
    expect(entry.gsi2pk).toBe(`TENANT#${TENANT_ID}#STUDENT#${STUDENT_ID}`);
  });
});
