/**
 * Validation Phase V1 — Synthetic Academic-Setup-Lifecycle Run
 *
 * Walks a brand-new PABSON school through the entire academic setup
 * lifecycle via API. Records observable behavior to inform:
 *   (a) pilot greenlight readiness for Saraswati real-prod
 *   (b) S2 sprint scope (UI/UX + presentation layer)
 *
 * This is NOT a smoke test (pass/fail). It is a FACT-GATHERING run
 * whose output is a structured technical documentation artifact.
 *
 * Target tenant + school
 * ======================
 *   Tenant: dev-pabson-primary (21aea5da-511f-4dfa-a6f2-6971f63a719f)
 *   School: Sunshine Private Academy (SPA983)
 *             3c28654f-c623-449b-8211-67c729784d37
 *   Status: Setup Mode (0 of 4 setup tasks complete)
 *
 * Hard-rejects real-prod Saraswati school 61a247a4-... at startup.
 *
 * Scenarios executed
 * ==================
 *   S1  Genesis — full PABSON 4-term setup (AY → calendar → 4 terms × 4 exam windows)
 *   S2  Holiday/exam collision — Term 2 exam window overlaps Dashain
 *   S3  Mid-year edit pattern — shrink + extend a term's exam window
 *   S4  Compliance / audit trail — query audit log for the entire lifecycle
 *
 * NOT exercised in this pass (need more API research first):
 *   - Bell Schedule (Step 4 of wizard)
 *   - Activation flow (POST /schools/:id/activate or similar)
 *
 * Output
 * ======
 *   - Captured findings as JSON: /tmp/v1-validation-findings.json
 *   - Markdown doc: docs/validation/academic-setup-lifecycle-2026-05-14.md
 *     (generated by a separate run after this script completes)
 *
 * Run:  npx ts-node scripts/smoke-tests/v1-academic-setup-lifecycle.ts
 */

import axios from 'axios';
import type { AxiosError } from 'axios';
import * as fs from 'fs';
import * as path from 'path';

// ============================================================================
// CONFIG
// ============================================================================

const BASE_URL =
  process.env.SMOKE_BASE_URL ||
  'https://w5ulch7iyf.execute-api.ap-south-1.amazonaws.com/prod';
const JWT_PATH = process.env.SMOKE_JWT_PATH || '/tmp/dev-jwt.txt';

const SCHOOL_ID: string = '3c28654f-c623-449b-8211-67c729784d37'; // Sunshine Private Academy
const REAL_PROD_SARASWATI: string = '61a247a4-44d6-4fc0-a414-062fd4d7e694';

const FINDINGS_PATH = '/tmp/v1-validation-findings.json';

if (SCHOOL_ID === REAL_PROD_SARASWATI) {
  console.error('FATAL: would not target real-prod Saraswati.');
  process.exit(2);
}
if (!fs.existsSync(JWT_PATH)) {
  console.error(`FATAL: ${JWT_PATH} missing.`);
  process.exit(2);
}

const RAW_JWT = fs.readFileSync(JWT_PATH, 'utf8').trim();
const AUTH = RAW_JWT.startsWith('Bearer ') ? RAW_JWT : `Bearer ${RAW_JWT}`;

const http = axios.create({
  baseURL: BASE_URL,
  headers: { Authorization: AUTH, 'Content-Type': 'application/json' },
  validateStatus: () => true,
  timeout: 30_000,
});

// ============================================================================
// COLORS + FINDINGS HARNESS
// ============================================================================

const C = {
  reset: '\x1b[0m', red: '\x1b[31m', green: '\x1b[32m', yellow: '\x1b[33m',
  cyan: '\x1b[36m', gray: '\x1b[90m', bold: '\x1b[1m', magenta: '\x1b[35m',
};

interface ApiCallRecord {
  method: string;
  url: string;
  status: number;
  durationMs: number;
  requestBody?: any;
  responseBody?: any;
  audit?: 'expected' | 'not-applicable';
}

interface Finding {
  id: string;
  severity: 'P0' | 'P1' | 'P2' | 'INFO';
  category: 'structural' | 'ux' | 'api-contract' | 'bug' | 'observation' | 'docs';
  title: string;
  description: string;
  evidence?: string;
  recommendation?: string;
}

interface ScenarioRun {
  id: string;
  name: string;
  startedAt: string;
  finishedAt?: string;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'skipped';
  apiCalls: ApiCallRecord[];
  findings: Finding[];
  observations: string[];
  stateDiff?: Record<string, any>;
}

interface ValidationRun {
  startedAt: string;
  finishedAt?: string;
  testSubstrate: {
    tenant: string;
    tenantId: string;
    school: string;
    schoolId: string;
    schoolShortCode: string;
    user: string;
    baseUrl: string;
  };
  scenarios: ScenarioRun[];
  globalFindings: Finding[];
}

const run: ValidationRun = {
  startedAt: new Date().toISOString(),
  testSubstrate: {
    tenant: 'dev-pabson-primary',
    tenantId: '21aea5da-511f-4dfa-a6f2-6971f63a719f',
    school: 'Sunshine Private Academy',
    schoolId: SCHOOL_ID,
    schoolShortCode: 'SPA983',
    user: 'rainshoaib01@gmail.com',
    baseUrl: BASE_URL,
  },
  scenarios: [],
  globalFindings: [],
};

let currentScenario: ScenarioRun | null = null;

function startScenario(id: string, name: string): ScenarioRun {
  console.log(`\n${C.bold}${C.cyan}═══ ${id} — ${name} ═══${C.reset}`);
  currentScenario = {
    id,
    name,
    startedAt: new Date().toISOString(),
    status: 'running',
    apiCalls: [],
    findings: [],
    observations: [],
  };
  run.scenarios.push(currentScenario);
  return currentScenario;
}

function finishScenario(status: 'completed' | 'failed' | 'skipped' = 'completed') {
  if (currentScenario) {
    currentScenario.finishedAt = new Date().toISOString();
    currentScenario.status = status;
    const colored = status === 'completed' ? C.green : status === 'failed' ? C.red : C.yellow;
    console.log(`${colored}── ${currentScenario.id} ${status} (${currentScenario.apiCalls.length} API calls)${C.reset}`);
    currentScenario = null;
  }
}

function note(msg: string) {
  console.log(`${C.gray}  · ${msg}${C.reset}`);
  if (currentScenario) currentScenario.observations.push(msg);
}

function recordFinding(f: Finding) {
  const colored = f.severity === 'P0' ? C.red : f.severity === 'P1' ? C.yellow : f.severity === 'P2' ? C.magenta : C.gray;
  console.log(`  ${colored}[${f.severity}/${f.category}] ${f.id}: ${f.title}${C.reset}`);
  console.log(`    ${C.gray}${f.description}${C.reset}`);
  if (currentScenario) currentScenario.findings.push(f);
  else run.globalFindings.push(f);
}

async function api(
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE',
  url: string,
  body?: any,
  opts: { audit?: 'expected' | 'not-applicable' } = {},
): Promise<{ status: number; data: any; durationMs: number }> {
  const start = Date.now();
  try {
    const res = await http({ method, url, data: body });
    const durationMs = Date.now() - start;
    const record: ApiCallRecord = {
      method,
      url,
      status: res.status,
      durationMs,
      requestBody: body,
      responseBody: res.data,
      audit: opts.audit,
    };
    if (currentScenario) currentScenario.apiCalls.push(record);
    const statusColor = res.status < 300 ? C.green : res.status < 500 ? C.yellow : C.red;
    console.log(`  ${statusColor}${res.status}${C.reset} ${method.padEnd(5)} ${url}  ${C.gray}${durationMs}ms${C.reset}`);
    return { status: res.status, data: res.data, durationMs };
  } catch (err) {
    const e = err as AxiosError;
    const durationMs = Date.now() - start;
    const status = e.response?.status ?? 0;
    const record: ApiCallRecord = {
      method, url, status, durationMs,
      requestBody: body, responseBody: e.response?.data ?? null, audit: opts.audit,
    };
    if (currentScenario) currentScenario.apiCalls.push(record);
    console.log(`  ${C.red}${status} ERR${C.reset} ${method} ${url}  ${C.gray}${durationMs}ms${C.reset}`);
    return { status, data: e.response?.data ?? null, durationMs };
  }
}

// ============================================================================
// MAIN
// ============================================================================

(async () => {
  console.log(`${C.bold}EdForge V1 — Academic Setup Lifecycle Validation${C.reset}`);
  console.log(`School: ${run.testSubstrate.school} (${SCHOOL_ID})`);
  console.log(`Tenant: ${run.testSubstrate.tenant} (${run.testSubstrate.tenantId})`);
  console.log(`Run at: ${run.startedAt}`);

  // ==========================================================================
  // PRE-FLIGHT
  // ==========================================================================
  startScenario('PRE', 'Pre-flight + initial state capture');

  const me = await api('GET', '/users/me');
  if (me.status !== 200) {
    recordFinding({
      id: 'F-V1-PRE-001',
      severity: 'P0', category: 'bug',
      title: 'JWT auth fails at /users/me',
      description: `GET /users/me returned ${me.status}`,
    });
    finishScenario('failed');
    save();
    process.exit(1);
  }
  note(`Authenticated as userId=${me.data.userId ?? me.data.id}`);

  const school = await api('GET', `/schools/${SCHOOL_ID}`);
  if (school.status !== 200) {
    recordFinding({
      id: 'F-V1-PRE-002',
      severity: 'P0', category: 'bug',
      title: 'School fetch fails',
      description: `GET /schools/${SCHOOL_ID} returned ${school.status}`,
    });
    finishScenario('failed');
    save();
    process.exit(1);
  }
  note(`School: "${school.data.name}" status=${school.data.status}`);

  // List existing AYs — should be empty for a fresh school
  const aysBefore = await api('GET', `/schools/${SCHOOL_ID}/academic-years`);
  const ayCountBefore = (aysBefore.data?.items ?? aysBefore.data ?? []).length;
  note(`Existing AY count: ${ayCountBefore}`);

  if (ayCountBefore !== 0) {
    recordFinding({
      id: 'F-V1-PRE-003',
      severity: 'INFO', category: 'observation',
      title: 'School is not greenfield — existing AYs present',
      description: `Expected fresh school but found ${ayCountBefore} existing AY(s). Test will create its own AY but findings may be confounded by prior state.`,
    });
  }
  finishScenario();

  // ==========================================================================
  // S1 — GENESIS (Full PABSON 4-term setup)
  // ==========================================================================
  const scenario1 = startScenario('S1', 'Genesis — full PABSON 4-term setup');

  // Step 1.1: Create AY for BS 2083
  const AY_NAME = `Validation-${Date.now().toString().slice(-6)}`;
  const ayCreate = await api('POST', `/schools/${SCHOOL_ID}/academic-years`, {
    name: AY_NAME,
    startDate: '2026-04-15',
    endDate: '2027-04-13',
    setAsCurrent: false,
  }, { audit: 'expected' });
  if (ayCreate.status !== 201 && ayCreate.status !== 200) {
    recordFinding({
      id: 'F-V1-S1-001',
      severity: 'P0', category: 'bug',
      title: 'AcademicYear create failed on greenfield school',
      description: `POST returned ${ayCreate.status}`,
      evidence: JSON.stringify(ayCreate.data).slice(0, 500),
    });
    finishScenario('failed');
    save();
    process.exit(1);
  }
  const yearId = ayCreate.data.yearId ?? ayCreate.data.id;
  note(`AY created: yearId=${yearId} name="${AY_NAME}"`);

  // Step 1.2: Generate calendar (Nepal locale, Saturday weekend, 30 holidays)
  const NEPAL_HOLIDAYS_2083 = [
    { date: '2026-05-01', name: 'May Day (International Labour Day)', eventType: 'holiday' },
    { date: '2026-05-11', name: 'Buddha Jayanti (Vesak)', eventType: 'holiday' },
    { date: '2026-05-29', name: 'Republic Day (Jestha 15)', eventType: 'holiday' },
    { date: '2026-07-17', name: 'Shrawan 1 (Start of Holy Month)', eventType: 'holiday' },
    { date: '2026-08-11', name: 'Janai Purnima / Raksha Bandhan', eventType: 'holiday' },
    { date: '2026-08-12', name: 'Gaijatra', eventType: 'holiday' },
    { date: '2026-08-14', name: 'Krishna Janmashtami', eventType: 'holiday' },
    { date: '2026-09-19', name: 'Constitution Day (Ashwin 3)', eventType: 'holiday' },
    { date: '2026-10-02', name: 'Ghatasthapana (Dashain begins)', eventType: 'holiday' },
    { date: '2026-10-09', name: 'Phulpati (Dashain)', eventType: 'holiday' },
    { date: '2026-10-10', name: 'Maha Ashtami (Dashain)', eventType: 'holiday' },
    { date: '2026-10-11', name: 'Maha Navami (Dashain)', eventType: 'holiday' },
    { date: '2026-10-12', name: 'Vijaya Dashami (Dashain)', eventType: 'holiday' },
    { date: '2026-10-13', name: 'Ekadashi (Dashain)', eventType: 'holiday' },
    { date: '2026-10-14', name: 'Dwadashi (Dashain)', eventType: 'holiday' },
    { date: '2026-10-20', name: 'Kojagrat Purnima', eventType: 'holiday' },
    { date: '2026-10-30', name: 'Laxmi Puja (Tihar)', eventType: 'holiday' },
    { date: '2026-10-31', name: 'Gobardhan Puja (Tihar)', eventType: 'holiday' },
    { date: '2026-11-01', name: 'Bhai Tika (Tihar)', eventType: 'holiday' },
    { date: '2026-11-02', name: 'Tihar Holiday', eventType: 'holiday' },
    { date: '2026-11-15', name: 'Chhath Parva', eventType: 'holiday' },
    { date: '2026-12-25', name: 'Christmas Day', eventType: 'holiday' },
    { date: '2027-01-01', name: 'New Year\'s Day (Gregorian)', eventType: 'holiday' },
    { date: '2027-01-14', name: 'Maghe Sankranti', eventType: 'holiday' },
    { date: '2027-01-29', name: 'Martyrs\' Day (Shahid Diwas)', eventType: 'holiday' },
    { date: '2027-02-19', name: 'Democracy Day (Falgun 7)', eventType: 'holiday' },
    { date: '2027-03-03', name: 'Maha Shivaratri', eventType: 'holiday' },
    { date: '2027-03-08', name: 'International Women\'s Day', eventType: 'holiday' },
    { date: '2027-03-17', name: 'Holi (Fagu Purnima)', eventType: 'holiday' },
    { date: '2027-03-29', name: 'Ghode Jatra', eventType: 'holiday' },
  ];

  const calGen = await api(
    'POST',
    `/schools/${SCHOOL_ID}/academic-years/${yearId}/generate-calendar`,
    {
      academicYearId: yearId,
      startDate: '2026-04-15',
      endDate: '2027-04-13',
      includeWeekends: false,
      schoolDays: ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
      holidays: NEPAL_HOLIDAYS_2083,
    },
    { audit: 'expected' },
  );
  if (calGen.status !== 201 && calGen.status !== 200) {
    recordFinding({
      id: 'F-V1-S1-002',
      severity: 'P0', category: 'bug',
      title: 'generate-calendar failed',
      description: `POST returned ${calGen.status}: ${JSON.stringify(calGen.data).slice(0, 300)}`,
    });
    finishScenario('failed');
    save();
    process.exit(1);
  }
  note(`Calendar generated: ${calGen.data.totalDays} total, ${calGen.data.instructionalDays} instructional, ${calGen.data.holidays} holidays, ${calGen.data.weekends} weekends`);

  // Step 1.3: Create 4 PABSON terms with exam windows
  const TERMS = [
    { name: 'Term 1', termType: 'quarter' as const, sequence: 1, startDate: '2026-04-15', endDate: '2026-07-15', examStartDate: '2026-07-06', examEndDate: '2026-07-10' },
    { name: 'Term 2', termType: 'quarter' as const, sequence: 2, startDate: '2026-07-16', endDate: '2026-10-15', examStartDate: '2026-10-05', examEndDate: '2026-10-09' },
    { name: 'Term 3', termType: 'quarter' as const, sequence: 3, startDate: '2026-10-16', endDate: '2027-01-15', examStartDate: '2027-01-05', examEndDate: '2027-01-09' },
    { name: 'Term 4', termType: 'quarter' as const, sequence: 4, startDate: '2027-01-16', endDate: '2027-04-13', examStartDate: '2027-04-05', examEndDate: '2027-04-09' },
  ];

  const createdTerms: { termId: string; name: string }[] = [];
  for (const t of TERMS) {
    const r = await api('POST', `/schools/${SCHOOL_ID}/academic-years/${yearId}/grading-periods`, t, { audit: 'expected' });
    if (r.status === 200 || r.status === 201) {
      const termId = r.data.termId ?? r.data.id;
      createdTerms.push({ termId, name: t.name });
      note(`${t.name} → ${termId}`);
    } else {
      recordFinding({
        id: `F-V1-S1-T${t.sequence}`,
        severity: 'P0', category: 'bug',
        title: `Term ${t.sequence} create failed`,
        description: `status=${r.status}: ${JSON.stringify(r.data).slice(0, 300)}`,
      });
    }
  }

  // Step 1.4: Verify auto-sync — count exam_window CalendarDate rows per term
  let totalExamRows = 0;
  for (const t of TERMS) {
    const cal = await api(
      'GET',
      `/schools/${SCHOOL_ID}/calendar-dates?academicYearId=${yearId}&startDate=${t.examStartDate}&endDate=${t.examEndDate}&limit=20`,
    );
    if (cal.status === 200) {
      const rows = ((cal.data?.items ?? cal.data) as any[]) ?? [];
      const examRows = rows.filter(r =>
        (r.calendarEvents ?? []).some((e: any) => e.eventType === 'exam_window'),
      );
      totalExamRows += examRows.length;
      const expected = 5; // 5-day exam windows
      if (examRows.length !== expected) {
        recordFinding({
          id: `F-V1-S1-AS${t.sequence}`,
          severity: 'P1', category: 'bug',
          title: `Term ${t.sequence}: auto-sync row count mismatch`,
          description: `Expected ${expected} exam_window rows for ${t.examStartDate}..${t.examEndDate}, got ${examRows.length}`,
          recommendation: 'Investigate auto-sync helper for off-by-one / range boundary handling.',
        });
      }
    }
  }
  note(`Total exam_window rows auto-synced across 4 terms: ${totalExamRows} (expected ~20)`);

  // Capture state diff
  scenario1.stateDiff = {
    academicYearsCreated: 1,
    termsCreated: createdTerms.length,
    examWindowRowsCreated: totalExamRows,
    holidayRowsCreated: calGen.data.holidays,
    instructionalDaysCreated: calGen.data.instructionalDays,
  };

  // Record positive finding — happy path observation
  if (createdTerms.length === 4 && totalExamRows === 20) {
    recordFinding({
      id: 'F-V1-S1-OK',
      severity: 'INFO', category: 'observation',
      title: 'PABSON 4-term genesis works end-to-end',
      description: `Created AY, generated 364-day calendar with 30 holidays, created 4 quarters, each with a 5-day exam window. Auto-sync produced 20 exam_window CalendarDate rows. Total API calls in this scenario: ${scenario1.apiCalls.length}. Cumulative API time: ${scenario1.apiCalls.reduce((s, c) => s + c.durationMs, 0)}ms.`,
    });
  }

  // API contract observation: how many calls did it take?
  recordFinding({
    id: 'F-V1-S1-API1',
    severity: 'INFO', category: 'api-contract',
    title: 'Setup requires N API calls to be operator-driven',
    description: `Full Genesis lifecycle took ${scenario1.apiCalls.length} API calls (1 create AY + 1 generate-calendar + 4 create-term). Each create-term auto-creates an AcademicSession AND auto-syncs 5 CalendarDate rows. Operator from UI experiences this as ~6 distinct UI actions if guided well.`,
  });

  finishScenario();

  // Save state for downstream scenarios
  const state = { yearId, termIds: createdTerms.map(t => t.termId), examStartDates: TERMS.map(t => t.examStartDate) };

  // ==========================================================================
  // S2 — HOLIDAY / EXAM COLLISION
  // ==========================================================================
  startScenario('S2', 'Holiday-Exam collision (Term 2 exam already overlaps Dashain)');

  // Term 2 exam: 2026-10-05 → 2026-10-09 (M-F)
  // Dashain holidays: 2026-10-02 (Fri Ghatasthapana), 2026-10-09 (Fri Phulpati)
  // → Term 2 exam window has 2026-10-09 which is ALSO a holiday.
  // Let's see what the data looks like on that date.
  const collisionRes = await api(
    'GET',
    `/schools/${SCHOOL_ID}/calendar-dates?academicYearId=${yearId}&startDate=2026-10-09&endDate=2026-10-09&limit=5`,
  );
  if (collisionRes.status === 200) {
    const rows = ((collisionRes.data?.items ?? collisionRes.data) as any[]) ?? [];
    const oct9 = rows.find(r => r.date === '2026-10-09');
    if (oct9) {
      const events = oct9.calendarEvents ?? [];
      const types = events.map((e: any) => e.eventType);
      note(`2026-10-09 (Phulpati) calendarEvents: [${types.join(', ')}]`);
      note(`isInstructionalDay=${oct9.isInstructionalDay} isHoliday=${oct9.isHoliday}`);

      if (types.includes('holiday') && types.includes('exam_window')) {
        recordFinding({
          id: 'F-V1-S2-COLLISION',
          severity: 'P1', category: 'structural',
          title: 'Backend silently accepts exam-window-during-holiday — no operator warning',
          description: `Term 2's exam window (2026-10-05..09) overlaps Phulpati (2026-10-09). The CalendarDate row for 2026-10-09 carries BOTH a holiday event AND an exam_window event. No validation rejects this. No warning is surfaced.`,
          evidence: `2026-10-09 calendarEvents=[${types.join(', ')}], isInstructionalDay=${oct9.isInstructionalDay}, isHoliday=${oct9.isHoliday}`,
          recommendation: 'Backend should NOT block (operator may legitimately schedule a make-up exam on a non-working day) but SHOULD return a warning in the response payload listing dates in the exam window that are also holidays. Frontend should surface this as a confirmation step at term-save time.',
        });
      } else {
        recordFinding({
          id: 'F-V1-S2-DATA',
          severity: 'INFO', category: 'observation',
          title: 'Holiday/exam collision data captured',
          description: `2026-10-09 events: [${types.join(', ')}]. Inspect manually.`,
        });
      }
    }
  }
  finishScenario();

  // ==========================================================================
  // S3 — MID-YEAR EDIT PATTERN (shrink + extend an exam window)
  // ==========================================================================
  startScenario('S3', 'Mid-year edit pattern — shrink + extend Term 1 exam window');

  const term1 = createdTerms[0];

  // Initial state: Term 1 exam 2026-07-06 → 2026-07-10 (5 days, 5 exam_window rows)
  note('Initial: Term 1 exam window 2026-07-06..10 (5 days)');

  // Shrink to 3 days: 2026-07-06 → 2026-07-08
  const shrink = await api(
    'PUT',
    `/schools/${SCHOOL_ID}/academic-years/${yearId}/grading-periods/${term1.termId}`,
    { examStartDate: '2026-07-06', examEndDate: '2026-07-08' },
    { audit: 'expected' },
  );
  note(`Shrink to 3 days → status ${shrink.status}`);

  await new Promise(r => setTimeout(r, 500)); // small wait for DDB consistency

  // Verify only 3 rows have our exam_window now
  const afterShrink = await api(
    'GET',
    `/schools/${SCHOOL_ID}/calendar-dates?academicYearId=${yearId}&startDate=2026-07-06&endDate=2026-07-10&limit=10`,
  );
  if (afterShrink.status === 200) {
    const rows = ((afterShrink.data?.items ?? afterShrink.data) as any[]) ?? [];
    const examRows = rows.filter(r =>
      (r.calendarEvents ?? []).some((e: any) => e.eventType === 'exam_window' && e.sourceTermId === term1.termId),
    );
    note(`After shrink: ${examRows.length} exam_window rows for our termId (expected: 3)`);
    if (examRows.length !== 3) {
      recordFinding({
        id: 'F-V1-S3-SHRINK',
        severity: 'P1', category: 'bug',
        title: 'Shrink left wrong number of exam_window rows',
        description: `Expected 3 rows for 2026-07-06..08; got ${examRows.length}. Dates seen: [${examRows.map(r => r.date).sort().join(', ')}]`,
      });
    }
  }

  // Extend to 7 days: 2026-07-06 → 2026-07-12 (includes Sat-Sun? July 11 is Sat, 12 is Sun)
  const extend = await api(
    'PUT',
    `/schools/${SCHOOL_ID}/academic-years/${yearId}/grading-periods/${term1.termId}`,
    { examStartDate: '2026-07-06', examEndDate: '2026-07-12' },
    { audit: 'expected' },
  );
  note(`Extend to 7 days (includes weekend) → status ${extend.status}`);

  await new Promise(r => setTimeout(r, 500));

  const afterExtend = await api(
    'GET',
    `/schools/${SCHOOL_ID}/calendar-dates?academicYearId=${yearId}&startDate=2026-07-06&endDate=2026-07-12&limit=10`,
  );
  if (afterExtend.status === 200) {
    const rows = ((afterExtend.data?.items ?? afterExtend.data) as any[]) ?? [];
    const examRows = rows.filter(r =>
      (r.calendarEvents ?? []).some((e: any) => e.eventType === 'exam_window' && e.sourceTermId === term1.termId),
    );
    note(`After extend (incl weekend): ${examRows.length} exam_window rows (expected: 7 — backend includes weekends in range)`);
    if (examRows.length !== 7) {
      recordFinding({
        id: 'F-V1-S3-EXTEND',
        severity: 'P1', category: 'bug',
        title: 'Extend produced wrong number of exam_window rows',
        description: `Expected 7 rows for 2026-07-06..12 (backend includes weekends); got ${examRows.length}. Dates seen: [${examRows.map(r => r.date).sort().join(', ')}]`,
      });
    }
    // Observation: weekend rows have exam_window event but are also weekend
    const weekendExamRow = examRows.find(r => r.dayOfWeek === 'saturday' || r.dayOfWeek === 'sunday');
    if (weekendExamRow) {
      const types = (weekendExamRow.calendarEvents ?? []).map((e: any) => e.eventType);
      recordFinding({
        id: 'F-V1-S3-WEEKEND-EXAM',
        severity: 'INFO', category: 'observation',
        title: 'Weekend dates inside exam window get exam_window event',
        description: `2026-07-${weekendExamRow.date.slice(-2)} (${weekendExamRow.dayOfWeek}) is in the exam range. CalendarDate has events=[${types.join(', ')}], isWeekend=${weekendExamRow.isWeekend}, isInstructionalDay=${weekendExamRow.isInstructionalDay}. Backend includes weekends in the auto-sync as designed.`,
        recommendation: 'Decide product semantic: should exam_window auto-sync skip weekends by default? PABSON schools typically don\'t run exams on Saturdays.',
      });
    }
  }

  finishScenario();

  // ==========================================================================
  // S4 — COMPLIANCE / AUDIT TRAIL
  // ==========================================================================
  startScenario('S4', 'Compliance — audit trail review for the full lifecycle');

  // Try to list audit log entries (may not have a public endpoint — observe contract)
  const auditAttempt = await api('GET', `/schools/${SCHOOL_ID}/audit-log?limit=50`);
  if (auditAttempt.status === 404) {
    recordFinding({
      id: 'F-V1-S4-NOAUDIT',
      severity: 'P1', category: 'api-contract',
      title: 'No public /audit-log endpoint',
      description: `GET /schools/${SCHOOL_ID}/audit-log returned 404. Audit rows exist in DDB (S0.8 AuditedWriteService writes them) but operators have no API path to view them. The Audit Log UI tab on School Details (visible in dev-pabson-primary) likely calls a different endpoint, or is reading via a non-standard route.`,
      recommendation: 'Identify the actual audit-log read endpoint used by AdminWeb. Document it. If not present, add one with stable contract.',
    });
  } else if (auditAttempt.status === 200) {
    const rows = ((auditAttempt.data?.items ?? auditAttempt.data) as any[]) ?? [];
    note(`Audit log returned ${rows.length} entries`);
    const examUpdates = rows.filter((r: any) => r.action === 'exam_dates_updated');
    const gradingCreates = rows.filter((r: any) => r.targetEntity === 'GRADING_PERIOD' && r.action === 'create');
    note(`GRADING_PERIOD create rows: ${gradingCreates.length}`);
    note(`exam_dates_updated rows: ${examUpdates.length}`);

    if (gradingCreates.length === 4 && examUpdates.length >= 2) {
      recordFinding({
        id: 'F-V1-S4-OK',
        severity: 'INFO', category: 'observation',
        title: 'Audit trail captures all S1 GradingPeriod operations',
        description: `4 GRADING_PERIOD create rows (one per term) + ${examUpdates.length} exam_dates_updated rows (from S3 mutations). The audit shape matches the S1.2 design.`,
      });
    }
  }

  finishScenario();

  // ==========================================================================
  // GLOBAL FINDINGS — observations applicable across scenarios
  // ==========================================================================

  // Structural smell from the user's earlier observation
  recordFinding({
    id: 'F-V1-STRUCT-001',
    severity: 'P1', category: 'structural',
    title: '"Regenerate Calendar" is a destructive default action in setup wizard',
    description: 'The Calendar wizard step exposes a "Regenerate Calendar" button that, on confirm, "delete all 364 existing calendar dates" — operator-entered overrides, teacher-only days, early-release events all destroyed. Modal admits its own design issue in the first sentence ("This is a destructive action"). A guided setup flow should not expose this as a primary action.',
    evidence: 'Modal screenshot captured during V1 validation: "Regenerate Calendar / This is a destructive action / This will delete all 364 existing calendar dates for 2083-academic-year and regenerate. Any manual edits (teacher in-service days, early releases, holiday overrides) will be permanently lost."',
    recommendation: 'Refactor: (1) Generate Calendar runs only ONCE during setup, gated behind "no calendar exists yet". (2) For modifications, provide scoped operations (add holiday, mark day as teacher-only, etc.) — never wipe-and-regenerate. (3) Reserve destructive reset to a deeply-guarded admin tool with typed confirmation. NOT a side button in the wizard.',
  });

  recordFinding({
    id: 'F-V1-STRUCT-002',
    severity: 'P2', category: 'structural',
    title: 'Operator can manually set exam_window via DateEditPanel — but should not',
    description: 'The wizard\'s inline DateEditPanel exposes "Exam Window" as one of the selectable event types in its dropdown. exam_window is a SERVER-MANAGED event (auto-synced from GradingPeriod.examStartDate/examEndDate). If an operator manually sets it on a date, it has no sourceTermId and will not be cleaned up when a term\'s exam dates change.',
    recommendation: 'Hide server-managed event types (exam_window) from the operator-facing dropdown. Or accept the manual case but warn: "This date is not linked to a term — the auto-sync will not manage it."',
  });

  // ==========================================================================
  // SUMMARY
  // ==========================================================================
  run.finishedAt = new Date().toISOString();
  console.log(`\n${C.bold}═══ SUMMARY ═══${C.reset}`);
  let totalApiCalls = 0, totalFindings = 0, p0 = 0, p1 = 0;
  for (const s of run.scenarios) {
    totalApiCalls += s.apiCalls.length;
    for (const f of s.findings) {
      totalFindings++;
      if (f.severity === 'P0') p0++;
      if (f.severity === 'P1') p1++;
    }
  }
  for (const f of run.globalFindings) {
    totalFindings++;
    if (f.severity === 'P0') p0++;
    if (f.severity === 'P1') p1++;
  }
  console.log(`Scenarios: ${run.scenarios.length}  API calls: ${totalApiCalls}  Findings: ${totalFindings}  P0: ${C.red}${p0}${C.reset}  P1: ${C.yellow}${p1}${C.reset}`);

  save();
  console.log(`\nFindings JSON: ${C.cyan}${FINDINGS_PATH}${C.reset}`);
  console.log(`Run the doc generator next:\n  ${C.gray}npx ts-node scripts/smoke-tests/v1-doc-generator.ts${C.reset}`);
})().catch(err => {
  console.error('Unhandled:', err);
  save();
  process.exit(1);
});

function save() {
  fs.writeFileSync(FINDINGS_PATH, JSON.stringify(run, null, 2));
}
