/**
 * Standardized error codes for the Finance service.
 *
 * Frontend can map these codes to i18n translation keys for localized messages.
 * Usage: throw new BadRequestException({ code: FinanceErrors.INVOICE_NOT_PAYABLE, message: '...' })
 */
export const FinanceErrors = {
  // Invoice errors
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_NOT_PAYABLE: 'INVOICE_NOT_PAYABLE',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  INVOICE_STATUS_TRANSITION: 'INVOICE_STATUS_TRANSITION',

  // Payment errors
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_EXCEEDS_DUE: 'PAYMENT_EXCEEDS_DUE',
  PAYMENT_VOID_NOT_COMPLETED: 'PAYMENT_VOID_NOT_COMPLETED',
  PAYMENT_REFUND_NOT_ELIGIBLE: 'PAYMENT_REFUND_NOT_ELIGIBLE',
  PAYMENT_REFUND_EXCEEDS_AMOUNT: 'PAYMENT_REFUND_EXCEEDS_AMOUNT',
  PAYMENT_SESSION_NOT_FOUND: 'PAYMENT_SESSION_NOT_FOUND',

  // Gateway errors
  GATEWAY_NOT_FOUND: 'GATEWAY_NOT_FOUND',
  GATEWAY_NOT_ENABLED: 'GATEWAY_NOT_ENABLED',
  GATEWAY_VERIFICATION_FAILED: 'GATEWAY_VERIFICATION_FAILED',
  GATEWAY_AMOUNT_MISMATCH: 'GATEWAY_AMOUNT_MISMATCH',

  // Fee structure errors
  FEE_STRUCTURE_NOT_FOUND: 'FEE_STRUCTURE_NOT_FOUND',

  // Account errors
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',

  // Concurrency
  CONCURRENT_UPDATE: 'CONCURRENT_UPDATE',
} as const;

export type FinanceErrorCode = typeof FinanceErrors[keyof typeof FinanceErrors];
