/*
 * Copyright EdForge.net, Inc. or its affiliates. All Rights Reserved.
 * 
 * Enrollment Service - Error Codes
 */

export enum ErrorCode {
  // Student errors
  STUDENT_NOT_FOUND = 'ENROLLMENT_STUDENT_NOT_FOUND',
  STUDENT_ALREADY_EXISTS = 'ENROLLMENT_STUDENT_ALREADY_EXISTS',
  INVALID_STUDENT_DATA = 'ENROLLMENT_INVALID_STUDENT_DATA',
  
  // Enrollment errors
  ENROLLMENT_NOT_FOUND = 'ENROLLMENT_NOT_FOUND',
  DUPLICATE_ENROLLMENT = 'ENROLLMENT_DUPLICATE',
  CAPACITY_EXCEEDED = 'ENROLLMENT_CAPACITY_EXCEEDED',
  INVALID_STATUS_TRANSITION = 'ENROLLMENT_INVALID_STATUS_TRANSITION',
  ACADEMIC_YEAR_NOT_ACTIVE = 'ENROLLMENT_ACADEMIC_YEAR_NOT_ACTIVE',
  
  // Finance-related errors
  INVOICE_NOT_FOUND = 'ENROLLMENT_INVOICE_NOT_FOUND',
  PAYMENT_ERROR = 'ENROLLMENT_PAYMENT_ERROR',
  
  // Validation errors
  VALIDATION_ERROR = 'ENROLLMENT_VALIDATION_ERROR',
  
  // System errors
  DATABASE_ERROR = 'ENROLLMENT_DATABASE_ERROR',
  TRANSACTION_FAILED = 'ENROLLMENT_TRANSACTION_FAILED'
}

