/**
 * Gateway Adapter Interface
 *
 * Each payment gateway (eSewa, Khalti, FonePay, etc.) implements this interface.
 * Adapters are stateless — credentials are passed in via GatewayConfig at call time.
 */

import type { GatewayConfigEntity } from '../../common/entities/gateway-config.entity';

/**
 * Input to initiatePayment — everything the adapter needs to build a redirect.
 */
export interface GatewayInitiateInput {
  /** Unique payment session ID (UUID) generated by PaymentsService */
  transactionId: string;
  /** Amount in NPR (e.g. 1500.00) */
  amount: number;
  /** Tax amount in NPR (default 0) */
  taxAmount: number;
  /** URL to redirect to on success (our callback endpoint) */
  successUrl: string;
  /** URL to redirect to on failure/cancel */
  failureUrl: string;
  /** Human-readable product/invoice description */
  productName: string;
}

/**
 * Result from initiatePayment — what the frontend needs to redirect the user.
 */
export interface GatewayInitiateResult {
  /** URL the frontend should redirect the user to (or POST form action URL) */
  redirectUrl: string;
  /** If the gateway uses form POST (eSewa), the form fields to submit */
  formData?: Record<string, string>;
  /** Gateway-assigned session/payment identifier (e.g. Khalti pidx) */
  gatewaySessionId?: string;
  /** When this payment session expires */
  expiresAt?: string;
  /** 'redirect' for simple URL redirect, 'form_post' for HTML form auto-submit */
  method: 'redirect' | 'form_post';
}

/**
 * Input to verifyPayment — gateway-specific callback data.
 */
export interface GatewayVerifyInput {
  /** Our internal transaction/session ID */
  transactionId: string;
  /** Amount to verify against */
  amount: number;
  /** Raw callback data from the gateway (query params or body) */
  callbackData: Record<string, string>;
}

/**
 * Result from verifyPayment — normalized verification outcome.
 */
export interface GatewayVerifyResult {
  /** Whether the payment is confirmed as successful */
  success: boolean;
  /** Gateway's transaction reference ID */
  gatewayTransactionId?: string;
  /** Normalized status */
  status: 'completed' | 'failed' | 'pending' | 'cancelled';
  /** Human-readable reason for failure (if failed) */
  failureReason?: string;
  /** Raw response from gateway (for debugging/audit) */
  rawResponse?: Record<string, unknown>;
}

/**
 * The contract every gateway adapter must implement.
 */
export interface GatewayAdapter {
  /** Gateway identifier — must match PaymentGateway enum value (e.g. 'esewa', 'khalti') */
  readonly gatewayName: string;

  /**
   * Initiate a payment session with the gateway.
   * Returns redirect URL or form data for the user to complete payment.
   */
  initiatePayment(
    input: GatewayInitiateInput,
    config: GatewayConfigEntity,
  ): Promise<GatewayInitiateResult>;

  /**
   * Verify a payment after the gateway callback redirect.
   * Calls the gateway's verification/lookup API.
   */
  verifyPayment(
    input: GatewayVerifyInput,
    config: GatewayConfigEntity,
  ): Promise<GatewayVerifyResult>;
}
